// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdiilreryoludwinxfnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkaWlscmVyeW9sdWR3aW54Zm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyMDk2NzcsImV4cCI6MjA4NDc4NTY3N30.L6OSntQQS39_odEyGBRG_Gid1OCOLuih1QzE3U_OctU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});